// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgpFtAd4x0_xJRrIG18UC24v7B1xGa_Q',
    appId: '1:384924126188:web:2993c050e55a9139678ec9',
    messagingSenderId: '384924126188',
    projectId: 'tager-2cbaf',
    authDomain: 'tager-2cbaf.firebaseapp.com',
    storageBucket: 'tager-2cbaf.firebasestorage.app',
    measurementId: 'G-TY2PEQ0PT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2BhhYjECPmB4erPkdb61LQOuBYsut6SQ',
    appId: '1:384924126188:android:807ee3a5b84c099b678ec9',
    messagingSenderId: '384924126188',
    projectId: 'tager-2cbaf',
    storageBucket: 'tager-2cbaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAew1-wXViYkfDz-8xwrv_DIzU_7ywI-ro',
    appId: '1:384924126188:ios:cf24b14b85bd7e4e678ec9',
    messagingSenderId: '384924126188',
    projectId: 'tager-2cbaf',
    storageBucket: 'tager-2cbaf.firebasestorage.app',
    androidClientId: '384924126188-e6citolqu01lsfumhn9p5req90jvvjct.apps.googleusercontent.com',
    iosClientId: '384924126188-f3de22gheljano6hjecvqjgv5v0lkdl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tageradmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAew1-wXViYkfDz-8xwrv_DIzU_7ywI-ro',
    appId: '1:384924126188:ios:cf24b14b85bd7e4e678ec9',
    messagingSenderId: '384924126188',
    projectId: 'tager-2cbaf',
    storageBucket: 'tager-2cbaf.firebasestorage.app',
    androidClientId: '384924126188-e6citolqu01lsfumhn9p5req90jvvjct.apps.googleusercontent.com',
    iosClientId: '384924126188-f3de22gheljano6hjecvqjgv5v0lkdl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tageradmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV5NuNCHjO1j000FVePBseq9s4vy7taKo',
    appId: '1:384924126188:web:a18f776d765f896b678ec9',
    messagingSenderId: '384924126188',
    projectId: 'tager-2cbaf',
    authDomain: 'tager-2cbaf.firebaseapp.com',
    storageBucket: 'tager-2cbaf.firebasestorage.app',
    measurementId: 'G-WGN6EN4N1V',
  );
}
